---
name: hochschule-burgenland-cluster-applications
description: "Hochschule Burgenland - Demo applications on the Kubernetes cluster"
visibility: public
protected: true
topics:
  - kubernetes
  - gitops
  - argocd
  - hochschule-burgenland

rulesets:
  branch:
    enabled: true
    requiredChecks:
      - Dependency Review
      - Lint

accessPermissions:
  vault:
    enabled: false
